### ISSUE TITLE
xmlschema validation problem

### ISSUE THREAD

**Issue by davlee1972** [brunato/xmlschema#13] opened 2017-07-10 21:39 UTC
I'm not sure what is causing the problem..

Error:

xmlschema.exceptions.XMLSchemaValidationError: failed validating <Element 'LegalType' at 0x7f69e86a79a8> with <XsdAttributeGroup at 0x7f69ea525710>.

Reason: '_Id' attribute not allowed for element.

Schema:

  <xs:restriction xmlns:xs="http://www.w3.org/2001/XMLSchema" base="SecIdAttrType">
                    <xs:maxLength value="30" />
  </xs:restriction>

Instance:

    <LegalType _Id="FE">FE</LegalType>

This fails:

        <xs:simpleType name="SecIdType">
                <xs:restriction base="xs:token">
                        <xs:maxLength value="10"/>
                </xs:restriction>
        </xs:simpleType>

        <xs:complexType name="SecIdAttrType">
                <xs:simpleContent>
                        <xs:extension base="xs:string">
                                <xs:attribute name="_Id" type="SecIdType" use="required"/>
                        </xs:extension>
                </xs:simpleContent>
        </xs:complexType>

        <xs:element name="LegalType">
                <xs:complexType>
                        <xs:simpleContent>
                                <xs:restriction base="SecIdAttrType">
                                        <xs:maxLength value="30"/>
                                </xs:restriction>
                        </xs:simpleContent>
                </xs:complexType>
        </xs:element>

But this works:

        <xs:simpleType name="ID_TYPE">
                <xs:restriction base="xs:token">
                        <xs:maxLength value="10"/>
                </xs:restriction>
        </xs:simpleType>

        <xs:simpleType name="STRING_30">
                <xs:restriction base="xs:string">
                        <xs:maxLength value="30"/>
                </xs:restriction>
        </xs:simpleType>

        <xs:complexType name="TYPE_ATTR_STRING_30">
                <xs:simpleContent>
                        <xs:extension base="STRING_30">
                                <xs:attribute name="_Id" type="ID_TYPE" use="required"/>
                        </xs:extension>
                </xs:simpleContent>
        </xs:complexType>

        <xs:element name="LegalType" type="TYPE_ATTR_STRING_30" minOccurs="0"/>

This schema validated fine in version 0.9.7. Think it was ok in 0.9.8 as well.

**Comment by brunato** [comment] 2017-07-12 13:03
The parsing of _simpleContent_ restriction was wrong, because the base attributes were not included in the restricted type. The issue is fixed in v0.9.11.

In the previous version I moved factories's code into the XSD components. This make the code more simple to maintain, but could happen that some schemas doesn't work anymore.

**Closed by brunato** 2017-07-12 13:03 UTC
