### ISSUE TITLE
IndexError occurs when validating schema using xs:all

### ISSUE THREAD

**Issue by ruffsl** [brunato/xmlschema#28] opened 2017-11-29 08:56 UTC
IndexError occurs while decoding children when validating schema using [`xs:all`](https://www.w3schools.com/xml/el_all.asp).

A minimal example:

xsd_string =
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="root" type="Root" />

    <xs:complexType name="Root">
        <xs:all>
            <xs:element name="foo" type="xs:string" />
            <xs:element name="bar" type="xs:string" />
        </xs:all>
    </xs:complexType>

</xs:schema>
``` 

xml_string_1 = 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<root>
    <foo>my_foo</foo>
    <bar>my_bar</bar>
</root>
```

xml_string_2 = 
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<root>
    <foo>my_foo</foo>
</root>
```

``` python
>>> import xmlschema
>>> print(xmlschema.__version__)
0.9.14
>>> xsd_schema = xmlschema.XMLSchema(xsd_string)
>>> print(xsd_schema.validate(data=xml_string_1, use_defaults=False))
None
>>> print(xsd_schema.validate(data=xml_string_2, use_defaults=False))
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-14-34fa9457033f> in <module>()
----> 1 xsd_schema.validate(data=xml_string_2, use_defaults=False)

/usr/local/lib/python3.5/dist-packages/xmlschema/xsdbase.py in validate(self, data, use_defaults)
    247         :raises: :exc:`XMLSchemaValidationError` if the object is not valid.
    248         """
--> 249         for error in self.iter_errors(data, use_defaults=use_defaults):
    250             raise error
    251 

/usr/local/lib/python3.5/dist-packages/xmlschema/xsdbase.py in iter_errors(self, data, path, use_defaults)
    261         :param use_defaults: Use schema's default values for filling missing data.
    262         """
--> 263         for chunk in self.iter_decode(data, path, use_defaults=use_defaults):
    264             if isinstance(chunk, XMLSchemaValidationError):
    265                 yield chunk

/usr/local/lib/python3.5/dist-packages/xmlschema/schema.py in iter_decode(self, xml_document, path, validation, process_namespaces, namespaces, use_defaults, decimal_type, converter, dict_class, list_class)
    428                 for obj in xsd_element.iter_decode(
    429                         xml_root, validation, use_defaults=use_defaults,
--> 430                         decimal_type=decimal_type, element_decode_hook=element_decode_hook):
    431                     yield obj
    432             else:

/usr/local/lib/python3.5/dist-packages/xmlschema/components/elements.py in iter_decode(self, elem, validation, **kwargs)
    310             if use_defaults and self.type.has_simple_content():
    311                 kwargs['default'] = self.default
--> 312             for result in self.type.iter_decode(elem, validation, **kwargs):
    313                 if isinstance(result, XMLSchemaValidationError):
    314                     if result.schema_elem is None:

/usr/local/lib/python3.5/dist-packages/xmlschema/components/complex_types.py in iter_decode(self, elem, validation, **kwargs)
    451         else:
    452             # Decode a complex content element
--> 453             for result in self.content_type.iter_decode(elem, validation, **kwargs):
    454                 if isinstance(result, XMLSchemaValidationError):
    455                     yield result

/usr/local/lib/python3.5/dist-packages/xmlschema/components/groups.py in iter_decode(self, elem, validation, **kwargs)
    287         while index < len(elem):
    288             obj = index
--> 289             for obj in self.iter_decode_children(elem, index=index):
    290                 if isinstance(obj, XMLSchemaValidationError):
    291                     yield obj

/usr/local/lib/python3.5/dist-packages/xmlschema/components/groups.py in iter_decode_children(self, elem, index)
    399                                 reason="child n.%d has a unexpected tag %r, must be one of %r." % (
    400                                     index + 1,
--> 401                                     qname_to_prefixed(elem[model_index].tag, self.namespaces),
    402                                     [qname_to_prefixed(e.name, self.namespaces) for e in group]
    403                                 ))

IndexError: child index out of range
```

Note that validation works fine when all required elements are present, but fails to return an expected `XMLSchemaValidationError` error when given xml data with a missing `bar` element.

**Comment by brunato** [comment] 2017-12-15 15:22
The issue is fixed now (new version 0.9.15). I've created a new exception class for element children validation. Also I've added test files for this issue.
Pay attention if you look at the code: several modules have been renamed or moved in order to make a code cleaning.
Thanks

**Closed by brunato** 2017-12-15 15:22 UTC

**Comment by ruffsl** [comment] 2017-12-16 09:31
Was it intentional not to expose the `XMLSchemaChildrenValidationError` class through the library module? Would be handy to expose as to be able to catch those exceptions specifically.

https://github.com/brunato/xmlschema/blob/e51d6d441bfc75c2a41eb2fb1ff2cdba1e2f4d9c/xmlschema/__init__.py#L18-L21

**Comment by brunato** [comment] 2017-12-16 10:00
No wasn't intentionally, I will include all significant exceptions in the library module.
Thanks
